### ISSUE TITLE
sentences_bert_sst2_rank_relevancies.npy file

### ISSUE THREAD

**Issue by akshay107** [mt-upc/transformer-contributions#1]
How to get sentences_{model_name}_sst2_rank_relevancies.npy file to check consistency in Text_classification.ipynb?

**Comment by javiferran** [comment]
Hi! Thanks for the comment.

Those `....npy` files are the stored attributions of each method for a particular model, and can be obtained via `attributions.py`.
Those were initial experiments measuring consistency in BERT vs. DistilBERT explanations. We eventually scaled the experiment and considered 10 BERT models from the [MultiBERT](https://huggingface.co/google/multiberts-seed_13) suite and computed the paper plots in [robustness.ipynb notebook](https://github.com/mt-upc/transformer-contributions/blob/main/robustness.ipynb).

**Comment by akshay107** [comment]
Hi, Thanks for your reply! Running attributions.py gave me two files {model_name}_sst2_attributions.npy and {model_name}_sst2_special_tok_attributions.npy. Using the two files, I was able to replicate most of Text_classification.ipynb except the consistency part. I'm still not able to generate sentences_{model_name}_sst2_rank_relevancies.npy. 

For robustness.ipynb, will it be possible for you to share multiberts-seed_{seed_i}_sst2_attributions.npy files for different seeds? Thanks!

**Comment by javiferran** [comment]
Hi,

I´m glad you could repoduce most of `Text_classification.ipynb`. The _consistency_ part of that notebook is from a previous old experiment and should have been removed from the notebook. As I mentioned earlier, we moved those experiments to `robustness.ipynb`. That being said, you should be able to obtain those results by using the BERT and DistilBERT `_sst2_attributions _attributions.npy` files instead of `rank_relevancies.npy`.

Regarding `robustness.ipynb`, I have computed the attributions and stored them (`multiberts-seed_{seed_i}_sst2_attributions.npy` files) in `./data` in the latest commit.

I hope that helps.

**Comment by akshay107** [comment]
Thanks for sharing the files! I'm able to run robustness.ipynb now.
